/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2ddf3f6b-1ad2-4304-843c-cf5a25dc9761",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_IJT2shorA",
    "aws_user_pools_web_client_id": "5e1m8pb9md3qvkc35tn074did4",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://jln3qk76wza2xjqz35onprvg64.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-i6z7itgq3vgmhfmc27ekue2ewy",
    "aws_user_files_s3_bucket": "rotarydatamain171248-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
